on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - run: go test -v ./...

      - run: |
          GOOS=darwin GOARCH=amd64 go build -o build/release/aoc24-darwin-amd64 cmd/aoc24/main.go
          GOOS=darwin GOARCH=arm64 go build -o build/release/aoc24-darwin-arm64 cmd/aoc24/main.go
          GOOS=linux GOARCH=amd64 go build -o build/release/aoc24-linux-amd64 cmd/aoc24/main.go
          GOOS=windows GOARCH=amd64 go build -o build/release/aoc24-windows-amd64.exe cmd/aoc24/main.go

      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: build/release

      - run: |
          VERSION=$(date +'%Y%m%d-%H%M')
          gh release create v$VERSION build/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
